import { useEffect, useRef, useState } from 'react';
import { Search, Clock, CalendarDays, Users, Layers, ChartNoAxesColumn, Sun, Moon, ArrowUp, Columns2, Table2, ChevronsUpDown, Menu, Settings, Minus, Square, X, PanelBottom, ChevronLeft, ChevronRight, FileText, Wifi, Volume2, Folder, Circle, Bell, Pin, Send, MessageCircle, Maximize2 } from 'lucide-react';

const icons = { find: Search, now: Clock, today: CalendarDays, people: Users, group: Layers, chart: ChartNoAxesColumn, sun: Sun, moon: Moon, send: ArrowUp, card: Columns2, table: Table2, chev: ChevronsUpDown, menu: Menu, settings: Settings, min: Minus, max: Square, close: X, mini: PanelBottom, prev: ChevronLeft, next: ChevronRight, cal: FileText, wifi: Wifi, volume: Volume2, folder: Folder, circle: Circle, bell: Bell, pin: Pin, feed: Send, chat: MessageCircle, expand: Maximize2 };
export function Icon({ name, size = 16, ...props }) { const Component = icons[name] || Circle; return <Component size={size} strokeWidth={1.5} aria-hidden="true" {...props} />; }
export function SeverityIcon({ severity, small = true }) {
  return <svg className={`ic${small ? ' sm' : ''}`} viewBox="0 0 24 24" role="img" aria-label={{ alarm: '경보', warning: '주의', caution: '알림' }[severity]}>
    {severity === 'alarm' ? <path d="M11.56 1.77c.19-.36.7-.36.88 0l10 19c.18.33-.07.73-.44.73H2c-.38 0-.62-.4-.44-.73l10-19Z" fill="var(--alarm)" stroke="var(--alarm-o)"/> : severity === 'warning' ? <circle cx="12" cy="12" r="9.5" fill="var(--warning)" stroke="var(--warning-o)"/> : <rect x="2.5" y="2.5" width="19" height="19" rx="1.5" fill="var(--caution)" stroke="var(--caution-o)"/>}
    <path d="M11 14V6h2v8h-2Zm2 2h-2v2h2v-2Z" fill={`var(--on-${severity})`}/>
  </svg>;
}
export function Button({ children, icon, primary, className = '', ...props }) { return <button type="button" className={`pbtn ${primary ? 'primary' : ''} ${className}`} {...props}>{icon && <Icon name={icon}/>} {children}</button>; }
export function IconButton({ icon, title, ...props }) { return <button type="button" className="tbtn" title={title} aria-label={title} {...props}><Icon name={icon}/></button>; }
export function Segmented({ options, value, onChange, label }) { return <div className="seg" role="group" aria-label={label}>{options.map(([key, title, icon]) => <button key={key} type="button" title={title} aria-label={title} aria-pressed={value === key} className={value === key ? 'on' : ''} onClick={() => onChange(key)}>{icon ? <Icon name={icon}/> : title}</button>)}</div>; }
export function SearchField({ value, onChange, placeholder = '이름 검색' }) { return <label className="fsearch"><Icon name="find"/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e => onChange(e.target.value)} onKeyDown={e => { if (e.key === 'Escape') onChange(''); }}/></label>; }
export function SelectField({ label, options, value, onChange }) { return <label className="pop select-field"><span>{label}</span><select aria-label={label} value={value} onChange={e => onChange(e.target.value)}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select><Icon name="chev" size={10}/></label>; }
export function Tabs({ options, value, onChange }) { return <div className="tabs" role="tablist">{options.map(([key, title]) => <button key={key} role="tab" aria-selected={key === value} className={key === value ? 'on' : ''} onClick={() => onChange(key)}>{title}</button>)}</div>; }
export function DataTable({ columns, rows, empty = '없음' }) { return <div className="table-scroll"><table className="dt"><thead><tr>{columns.map((c, i) => <th key={`${c}-${i}`} scope="col">{c}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, i) => <tr key={row.id ?? i}>{(row.cells || row).map((cell, j) => <td key={j}>{cell}</td>)}</tr>) : <tr><td colSpan={columns.length} className="empty">{empty}</td></tr>}</tbody></table></div>; }
export function Progress({ student, value }) { return student ? <div className="track" aria-label={`진행 ${student.cur}/${student.total}`}>{Array.from({ length: student.total }, (_, k) => <i key={k} className={student.wrong.includes(k + 1) && k + 1 <= student.cur ? 'w' : k + 1 < student.cur || ['done', 'ended'].includes(student.st) && k + 1 <= student.cur ? 'd' : k + 1 === student.cur && student.st === 'live' ? 'c' : ''}/>)}</div> : <><span className="pbar"><i style={{ width: `${Math.max(0, Math.min(100, value))}%` }}/></span><span className="mut num">{value}%</span></>; }
export function Kpis({ items }) { return <div className="kpis">{items.map(([label, value, sub]) => <div className="kpi" key={label}><div className="l">{label}</div><div className="v num">{value}</div><div className="s">{sub}</div></div>)}</div>; }
export function FormRow({ label, children }) { return <div className="frow"><div className="fl">{label}</div><div className="fc">{children}</div></div>; }
export function Toggle({ label, value, onChange }) { const [local, setLocal] = useState(true); const on = value ?? local; return <button className={`switch ${on ? 'on' : ''}`} role="switch" aria-checked={on} aria-label={label} onClick={() => onChange ? onChange(!on) : setLocal(!on)}><i/></button>; }
export function Modal({ title, children, onClose, actions, wide = false }) {
  const ref = useRef(null);
  useEffect(() => { const previous = document.activeElement; const dialog = ref.current; dialog.showModal(); return () => { dialog.close(); if (previous instanceof HTMLElement && previous.isConnected) previous.focus(); }; }, []);
  return <dialog ref={ref} className={`react-dialog ${wide ? 'wide' : ''}`} aria-label={title} onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === ref.current) { const r = ref.current.getBoundingClientRect(); if (e.clientX < r.left || e.clientX > r.right || e.clientY < r.top || e.clientY > r.bottom) onClose(); } }}><div className="mtitle">{title}<IconButton icon="close" title="닫기" onClick={onClose}/></div><div className="mbody">{children}</div>{actions && <div className="macts">{actions}</div>}</dialog>;
}
export function WindowTitle({ title, onMinimize, onMaximize, onClose, children, onPointerDown, onDoubleClick }) { return <div className="wtitle" onPointerDown={onPointerDown} onDoubleClick={onDoubleClick}><div className="appic-s">밀</div>{children}<div className="wt-name">{title}</div><div className="sp"/><div className="caps">{onMinimize && <button className="cap" title="최소화" aria-label="최소화" onClick={onMinimize}><Icon name="min"/></button>}{onMaximize && <button className="cap" title="최대화/이전 크기" aria-label="최대화/이전 크기" onClick={onMaximize}><Icon name="max"/></button>}{onClose && <button className="cap close" title="닫기" aria-label="닫기" onClick={onClose}><Icon name="close"/></button>}</div></div>; }
