import { useRef, useState } from 'react';
import { deskRect, useFloatingWindow } from './windowing.js';
import { WindowTitle, FormRow, Toggle, DataTable, Button, Segmented } from './components.jsx';

const shortcuts = [['N', '다음 확인 필요 학생'], ['↑ ↓', '보드에서 확인 필요 학생 이동 · 학생 상세에서 옆 학생'], ['Enter', '학생 열기'], ['Ctrl / ⌘ + K', '학생 · 명령 검색'], ['Ctrl / ⌘ + B', '탐색 창'], ['Ctrl / ⌘ + W', '앞에 있는 창 닫기'], ['Ctrl / ⌘ + Shift + M', '미니 창'], ['Ctrl / ⌘ + , ', '설정'], ['Ctrl / ⌘ + 1 / 2', '지금 수업 / 오늘 전체'], ['Alt + 1~9', '학생 탭 이동'], ['← →', '문항 이동'], ['F', '학생 화면 따라가기'], ['Alt + T', '주간 · 야간']];
export default function Settings({ state, dispatch, onClose, notify, onAction, initialTab = 'account', setMode, z, active = true, onFocus }) {
  const [tab, setTab] = useState(initialTab);
  const start = useRef(null);
  if (!start.current) { const d = deskRect(); const w = Math.min(900, d.width - 32), h = Math.min(600, d.height - 32); start.current = { x: Math.max(8, (d.width - w) / 2), y: Math.max(8, (d.height - h) / 2), w, h }; }
  const win = useFloatingWindow({ minW: 640, minH: 420, initial: start.current, onInteract: onFocus });
  const pref = (key, fallback = true) => state.preferences[key] ?? fallback;
  const toggle = (key, fallback = true) => <Toggle label={key} value={pref(key, fallback)} onChange={value => dispatch({ type: 'preference', key, value })}/>;
  const options = [['account', '계정'], ['notify', '알림'], ['keys', '단축키'], ['snip', '상용구'], ['window', '창 · 배치'], ['display', '표시'], ['update', '업데이트']];
  return <section className={`win topw setw settings-window ${win.maximized ? 'max' : ''} ${active ? '' : 'inactive'}`} style={{ ...win.style, zIndex: z }} onPointerDown={onFocus} role="dialog" aria-modal="false" aria-label="설정"><WindowTitle title="설정 - 밀당 LMS" {...win.titleProps} onMinimize={onClose} onMaximize={win.toggleMax} onClose={onClose}/><div className="set-body"><aside className="sidebar"><div className="sb-scroll">{options.map(([key, label]) => <button className={`sb-i ${key === tab ? 'on' : ''}`} key={key} onClick={() => setTab(key)}>{label}</button>)}</div></aside><div className="set-main scroll">
    {tab === 'account' && <><h3>계정</h3><FormRow label="이름">강은화</FormRow><FormRow label="이메일">kangeh@mildang.kr</FormRow><FormRow label="역할">선생님 · 고1 수학 A반 외 3</FormRow><div className="note mut">로컬 데모 계정입니다. 실제 계정과 연결되어 있지 않습니다.</div><h3>세션</h3><FormRow label="자동 로그인">{toggle('자동 로그인')}</FormRow><FormRow label="컴퓨터 켜면 실행"><span className="mut">웹 데모에서는 지원하지 않음</span></FormRow></>}
    {tab === 'notify' && <><h3>알림 규칙</h3><div className="note mut">데모 화면의 확인 필요 상태로 표시합니다. OS 알림은 전송하지 않습니다.</div><DataTable columns={['상황', '등급', '알림', '소리', '자동 닫힘']} rows={ [['수업 시간인데 미접속', '경보', '안 닫힘'], ['문항에서 10분째 멈춤', '경보', '안 닫힘'], ['접속 후 5분째 미시작', '주의', '10초'], ['연속 오답 3회', '주의', '10초'], ['새 채팅 · 3분 미응답', '주의', '10초'], ['새 채팅', '알림', '10초'], ['학습 완료 · 종료 대기', '알림', '-']].map(([text, sev, dismiss]) => [text, sev, toggle(`${text} 알림`), toggle(`${text} 소리`, sev === '경보'), dismiss]) }/><h3>방해 금지</h3><FormRow label="수업 시간 외">{toggle('방해 금지')} 22:30 – 다음날 19:00</FormRow></>}
    {tab === 'keys' && <><h3>단축키</h3><DataTable columns={['키', '동작']} rows={shortcuts.map(([key, label]) => [<kbd className="kb">{key}</kbd>, label])}/></>}
    {tab === 'snip' && <><h3>상용구</h3><div className="mut">채팅 입력창에서 /잠깐, /다시를 입력하면 학생 이름과 문항이 채워집니다.</div><DataTable columns={['단축어', '문구', '공유']} rows={ [['잠깐', '잠깐 볼게요, {이름}!', '나만'], ['다시', '{문항}번 다시 한번 풀어볼까?', '팀'], ['칭찬', '오늘 정말 잘했어요 👍', '팀'], ['종료', '오늘 수업 여기까지! 내일 봐요', '나만']].map(([key, text, share]) => [<kbd className="kb">/{key}</kbd>, text, share]) }/></>}
    {tab === 'window' && <><h3>창 배치</h3><FormRow label="학생 상세 창">처음 열 때 보드 옆에 나란히</FormRow><h3>작업 모드</h3><DataTable columns={['모드', '배치', '']} rows={ [['수업 모드', '보드 · 학생 상세', 'split-view'], ['첨삭 모드', '학생 상세 최대화', 'maximized'], ['작은 창', '드래그 가능한 학생 창', 'floating']].map(([label, text, mode]) => [label, text, <button className="lnk" onClick={() => { setMode(mode); onClose(); notify(`${label} 배치를 적용했습니다`); }}>지금 적용</button>]) }/><div className="note mut">브라우저 안에서 창을 배치합니다. OS 항상 위 기능은 지원하지 않습니다.</div></>}
    {tab === 'display' && <><h3>표시</h3><FormRow label="테마"><Segmented label="테마" value={state.theme} options={ [['day', '주간'], ['dusk', '야간']] } onChange={theme => dispatch({ type: 'theme', theme })}/></FormRow><FormRow label="글자 크기"><Segmented label="글자 크기" value={pref('fontSize', 'normal')} options={ [['small', '작게'], ['normal', '보통'], ['large', '크게']] } onChange={value => dispatch({ type: 'preference', key: 'fontSize', value })}/></FormRow><FormRow label="보드 밀도"><Segmented label="보드 밀도" value={pref('density', 'normal')} options={ [['wide', '넓게'], ['normal', '보통'], ['compact', '좁게']] } onChange={value => dispatch({ type: 'preference', key: 'density', value })}/></FormRow></>}
    {tab === 'update' && <><h3>업데이트</h3><FormRow label="현재 버전">1.0.0 (React 데모)</FormRow><FormRow label="저장 방식">이 브라우저의 로컬 저장소</FormRow><div className="acts"><Button onClick={() => { dispatch({ type: 'simulate' }); notify('최지우의 새 채팅을 시뮬레이션했습니다'); }}>새 채팅 시뮬레이션</Button><Button className="danger" onClick={() => onAction('reset')}>데모 데이터 초기화…</Button></div><div className="note mut">초기화하면 채팅, 메모, 피드 예약 및 설정이 원래 상태로 돌아갑니다.</div></>}
  </div></div><div className="statusbar"><span className="route-code">/settings/{tab}</span></div>
    {!win.maximized && <div className="rs" {...win.resizeProps} role="presentation"/>}</section>;
}
